// <auto-generated />
namespace FilmsApp.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class changeModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeModels));
        
        string IMigrationMetadata.Id
        {
            get { return "201709021655131_changeModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
